// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ServiceLayer;

namespace ServiceLayer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ServiceLayer.Model.Actor", b =>
                {
                    b.Property<int>("ActorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ActorTypeId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("InsertedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ActorId");

                    b.HasIndex("ActorTypeId");

                    b.ToTable("Actors");

                    b.HasData(
                        new
                        {
                            ActorId = 1,
                            ActorTypeId = 1,
                            FirstName = "Allu",
                            InsertedDate = new DateTime(2020, 7, 6, 22, 16, 1, 123, DateTimeKind.Local).AddTicks(5930),
                            LastName = "Arjun"
                        },
                        new
                        {
                            ActorId = 2,
                            ActorTypeId = 1,
                            FirstName = "Ravi",
                            InsertedDate = new DateTime(2020, 7, 6, 22, 16, 1, 137, DateTimeKind.Local).AddTicks(510),
                            LastName = "Teja"
                        },
                        new
                        {
                            ActorId = 3,
                            ActorTypeId = 1,
                            FirstName = "Shree",
                            InsertedDate = new DateTime(2020, 7, 6, 22, 16, 1, 137, DateTimeKind.Local).AddTicks(530),
                            LastName = "Ram"
                        },
                        new
                        {
                            ActorId = 4,
                            ActorTypeId = 1,
                            FirstName = "Jnr",
                            InsertedDate = new DateTime(2020, 7, 6, 22, 16, 1, 137, DateTimeKind.Local).AddTicks(530),
                            LastName = "Ntr"
                        },
                        new
                        {
                            ActorId = 5,
                            ActorTypeId = 1,
                            FirstName = "Mahesh",
                            InsertedDate = new DateTime(2020, 7, 6, 22, 16, 1, 137, DateTimeKind.Local).AddTicks(530),
                            LastName = "Babu"
                        },
                        new
                        {
                            ActorId = 6,
                            ActorTypeId = 1,
                            FirstName = "Kamal",
                            InsertedDate = new DateTime(2020, 7, 6, 22, 16, 1, 137, DateTimeKind.Local).AddTicks(540),
                            LastName = "Hasan"
                        });
                });

            modelBuilder.Entity("ServiceLayer.Model.ActorType", b =>
                {
                    b.Property<int>("ActorTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ActorTypeId");

                    b.ToTable("ActorTypes");

                    b.HasData(
                        new
                        {
                            ActorTypeId = 1,
                            Name = "Actor"
                        });
                });

            modelBuilder.Entity("ServiceLayer.Model.Movie", b =>
                {
                    b.Property<int>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("InsertedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.HasKey("MovieId");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            InsertedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Kalyanam",
                            Rating = 4,
                            ReleaseDate = new DateTime(2020, 7, 6, 22, 16, 1, 137, DateTimeKind.Local).AddTicks(2750)
                        },
                        new
                        {
                            MovieId = 2,
                            InsertedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Don",
                            Rating = 5,
                            ReleaseDate = new DateTime(2020, 7, 6, 22, 16, 1, 137, DateTimeKind.Local).AddTicks(3470)
                        });
                });

            modelBuilder.Entity("ServiceLayer.Model.MovieDetail", b =>
                {
                    b.Property<int>("MovieDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ActorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("InsertedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.HasKey("MovieDetailId");

                    b.HasIndex("ActorId");

                    b.HasIndex("MovieId");

                    b.ToTable("MovieDetails");
                });

            modelBuilder.Entity("ServiceLayer.Model.Actor", b =>
                {
                    b.HasOne("ServiceLayer.Model.ActorType", null)
                        .WithMany("Actors")
                        .HasForeignKey("ActorTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ServiceLayer.Model.MovieDetail", b =>
                {
                    b.HasOne("ServiceLayer.Model.Actor", "Actor")
                        .WithMany("MovieDetails")
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ServiceLayer.Model.Movie", "Movie")
                        .WithMany()
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
